// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJuzxll4POcEe6tq_npo0POWYKxWcAebQ',
    appId: '1:784318896518:android:13d9171c7f691afe45f407',
    messagingSenderId: '784318896518',
    projectId: 'to-do-app-dc50e',
    storageBucket: 'to-do-app-dc50e.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa60YsxxjCyoZSnw3QO-IT7zV3sQJbEmw',
    appId: '1:784318896518:web:baffbde63bc2b72845f407',
    messagingSenderId: '784318896518',
    projectId: 'to-do-app-dc50e',
    authDomain: 'to-do-app-dc50e.firebaseapp.com',
    storageBucket: 'to-do-app-dc50e.appspot.com',
    measurementId: 'G-DZLK8SL7JH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqh4Vf_PbEp9Ei88Ftabtm1UDai2R9YoE',
    appId: '1:784318896518:ios:56129835a55bf16345f407',
    messagingSenderId: '784318896518',
    projectId: 'to-do-app-dc50e',
    storageBucket: 'to-do-app-dc50e.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqh4Vf_PbEp9Ei88Ftabtm1UDai2R9YoE',
    appId: '1:784318896518:ios:56129835a55bf16345f407',
    messagingSenderId: '784318896518',
    projectId: 'to-do-app-dc50e',
    storageBucket: 'to-do-app-dc50e.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa60YsxxjCyoZSnw3QO-IT7zV3sQJbEmw',
    appId: '1:784318896518:web:ed58161c2a4b4ddd45f407',
    messagingSenderId: '784318896518',
    projectId: 'to-do-app-dc50e',
    authDomain: 'to-do-app-dc50e.firebaseapp.com',
    storageBucket: 'to-do-app-dc50e.appspot.com',
    measurementId: 'G-J67YYB9ZF0',
  );

}